import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          'login_title': 'Login',
          'otp_title': 'OTP\nVerification',
          'login_subtitle': 'Please enter your login details  below.',
          'otp_subtitle': 'Enter your OTP code here',
          'notgetOTP': 'Didn’t get code yet?',
          "email": "Email",
          "password": "Password",
          "remember_me": "Remember Me",
          "forgot_password": "Forgot Password?",
          "login_CTA": "Login",
          "forgot_your_password_title": "Forgot Your\nPassword?",
          "forgot_your_password_subtitle": "Enter your registered email below\nto receive password reset instruction.",
          "continue_CTA":"Continue",
          "remember_password": "Remember Password?",
          "create_new_password_title":"Create New\nPassword",
          "create_new_password_subtitle": "Your new password must be different\nfrom previous used password.",
          "old_password": "Old Password",
          "new_password": "New Password",
          "confirm_new_password": "Confirm New Password",
          "reset_password_CTA": "Reset Password",
          "driver_report_title": "Driver Report",
          "submit_CTA": "Submit",
          "home_subtitle": "Please select your vehicle to\naccess this app",
          "car": "Car",
          "profile_title": "Profile",
          "edit_profile_CTA": "Edit Profile",
          "scan_the_qr_code_to_start": "Scan the QR Code\nto Start",
          "privacy": "Privacy",
          "changePassword": "Change Password",
          "help": "Help",
          "log_out": "Log out",
          "total_passenger_title": "Total Passenger",
          "search": "Search",
          "swipe_to_complete_CTA": "Swipe to Complete",
          "pickup_passengers_CTA": "Pickup Passengers",
          "show_passengers_CTA": "Show Passengers",
          "swipe_to_start_CTA": "Swipe to Start",
          "start_location": "Start Location",
          "destination": "Destination",
          "passenger_details" : "Passenger Details",
          "total_passengers": "Total Passengers",
          "inside_bus": "Inside Bus",
          "vehicle_details": "Vehicle Details",
          "scan_qr_code_CTA": "Scan QR Code",
          "get_otp_CTA": "Get OTP",
          "vehicle": "Vehicle",
          "plate_no": "Plate No.",
          "vehicle_id": "Vehicle ID",
          "seats": "Seats",
          "fuel": "Fuel",
          "check_in": "Check In :",
          "notification_title": "Notification",
          "full_name": "Full Name",
          "address": "Address",
          "current_pick_up_stop": "Current Pick up Stop",
          "change_address_CTA": "Change Address",
          "settings_title": "Settings",
          "search_here": "Search Here",
          "new_pickup_address": "New Pickup Address",
          "adress_change_request": "Address Change Request",
          "upload_bill_CTA": "Upload your Utility bill",
          "confirm_location_CTA": "Confirm Location",
          "language":"Language",
          "noInternet":"No Internet! Please Check Your Internet And Try Again",
           "noRouteFoundDriver":"No Rout found!",
           "noRouteFoundPassenger":" No Rout found!",
           "checkIn":" Check In",
        },
        "es_ES": {
          'login_title': 'Acceso',
          'otp_title': 'OTP \n Verification',
          'otp_subtitle': 'Enter your OTP code here',
          'login_subtitle': 'Por favor, introduzca sus datos de acceso.',
          'notgetOTP': 'Didn’t get code yet?',
          "email": "Correo Electrónico",
          "password": "Contraseña",
          "email_validation": "¡Por favor, introduzca su correo electrónico!",
          "password_validation": "¡Por favor, introduzca su contraseña!",
          "remember_me": "Guardar mis datos de acceso",
          "forgot_password": "¿Has olvidado la contraseña?",
          "login_CTA": "Login",
          "forgot_your_password_title": "¿Has olvidado\nla contraseña?",
          "forgot_your_password_subtitle": "Introduzca el correo electrónico utilizado en su registro\npara recibir instrucciones sobre cómo restablecer la contraseña.",
          "continue_CTA": "Continuar",
          "remember_password": "¿Recordar contraseña?",
          "create_new_password_title": "Crear nueva\ncontraseña",
          "create_new_password_subtitle": "Su nueva contraseña debe ser diferente\nde la contraseña utilizada anteriormente.",
          "old_password": "Old Password",
          "new_password": "Nueva contraseña",
          "confirm_new_password": "Confirmar nueva contraseña",
          "reset_password_CTA": "Restablecer contraseña",
          "driver_report_title": "Informe del conductor",
          "submit_CTA": "Enviar",
          "home_subtitle": "Por favor, seleccione su vehículo\npara acceder a esta aplicación.",
          "car": "Vehículo",
          "profile_title": "Perfil",
          "edit_profile_CTA": "Editar perfil",
          "scan_the_qr_code_to_start": "Escanee el código QR\npara empezar",
          "privacy": "Privacidad",
          "changePassword": "Change Password",
          "help": "Ayuda",
          "log_out": "Cerrar sesión",
          "total_passenger_title": "Número de pasajeros",
          "search": "Búsqueda",
          "swipe_to_complete_CTA": "Deslizar para completar",
          "pickup_passengers_CTA": "Embarque de pasajeros",
          "show_passengers_CTA": "Mostrar pasajeros",
          "swipe_to_start_CTA": "Deslizar para empezar",
          "start_location": "Lugar de inicio",
          "destination": "Destino",
          "passenger_details" : "Datos del pasajero",
          "total_passengers": "Número de pasajeros",
          "inside_bus": "Dentro del autobús",
          "vehicle_details": "Datos del vehículo",
          "scan_qr_code_CTA": "Escanear el código QR",
          "get_otp_CTA": "Get OTP",
          "vehicle": "Vehículo",
          "plate_no": "Matrícula",
          "vehicle_id": "ID del vehículo",
          "seats": "Asientos",
          "fuel": "Combustible",
          "check_in": "Check In",
          "notification_title": "Notificación",
          "full_name": "Nombre completo",
          "address": "Dirección",
          "current_pick_up_stop": "Parada actual",
          "change_address_CTA": "Cambiar dirección",
          "settings_title": "Ajustes",
          "search_here": "Buscar aquí",
          "new_pickup_address": "Dirección de la nueva parada",
          "adress_change_request": "Address Change Request",
          "upload_bill_CTA": "Cargar factura de servicio",
          "confirm_location_CTA": "Confirmar dirección",
          "language": "Idioma",
          "noInternet": "¡Sin Internet! Por favor, compruebe su conexión a internet e inténtelo de nuevo.",
          "checkIn": "registrarse",
        },
        "pt_PT": {
          'login_title': 'Conecte-se',
          'otp_title': 'OTP \n Verification',
          'otp_subtitle': 'Enter your OTP code here',
          'login_subtitle': 'Por favor, preencha seus dados para fazer login abaixo.',
          'notgetOTP': 'Didn’t get code yet?',
          "email": "E-mail",
          "password": "Senha",
          "email_validation": "Por favor, digite seu e-mail!",
          "password_validation": "Por favor, digite sua senha!",
          "remember_me": "Salvar meus dados de login",
          "forgot_password": "Esqueceu sua senha?",
          "login_CTA": "Login",
          "forgot_your_password_title": "Esqueceu sua\nsenha?",
          "forgot_your_password_subtitle": "Digite o e-mail usado no seu registro\npara receber instruções sobre como criar uma nova senha",
          "continue_CTA": "Continuar",
          "remember_password": "Lembrar senha?",
          "create_new_password_title":"Criar nova\nsenha",
          "create_new_password_subtitle": "Sua nova senha deve ser diferente\nda senha usada anteriormente.",
          "old_password": "Old Password",
          "new_password": "Nova senha",
          "confirm_new_password": "Confirmar nova senha",
          "reset_password_CTA": "Redefinir senha",
          "driver_report_title": "Relatório do motorista",
          "submit_CTA": "Enviar",
          "home_subtitle": "Selecione seu veículo para\nacessar este aplicativo",
          "car": "Veículo",
          "profile_title": "Perfil",
          "edit_profile_CTA": "Editar perfil",
          "scan_the_qr_code_to_start": "Escaneie o QR code\npara iniciar",
          "privacy": "Privacidade",
          "changePassword": "Change Password",
          "help": "Ajuda",
          "log_out": "Sair",
          "total_passenger_title": "Quantidade de passageiros",
          "search": "Pesquisar",
          "swipe_to_complete_CTA": "Deslize para concluir",
          "pickup_passengers_CTA": "Embarque de passageiros",
          "show_passengers_CTA": "Mostrar passageiros",
          "swipe_to_start_CTA": "Deslizar para iniciar",
          "start_location": "Local de início",
          "destination": "Destino",
          "passenger_details" : "Dados de passageiros",
          "total_passengers": "Quantidade de passageiros",
          "inside_bus": "Dentro do ônibus",
          "vehicle_details": "Dados do veículo",
          "scan_qr_code_CTA": "Escaneie o QR code",
          "get_otp_CTA": "Get OTP",
          "vehicle": "Veículo",
          "plate_no": "Placa",
          "vehicle_id": "ID do veículo",
          "seats": "Assentos",
          "fuel": "Combustível",
          "check_in": "Check-in",
          "notification_title": "Notificação",
          "full_name": "Nome completo",
          "address": "Endereço",
          "current_pick_up_stop": "Ponto atual",
          "change_address_CTA": "Alterar endereço",
          "settings_title": "Configurações",
          "search_here": "Pesquisar aqui",
          "new_pickup_address": "Endereço do novo ponto",
          "adress_change_request": "Address Change Request",
          "upload_bill_CTA": "Fazer upload de comprovante de endereço",
          "confirm_location_CTA": "Confirmar localização",
          "language": "Idioma",
          "noInternet": "Sem internet! Por favor, verifique sua internet e tente novamente.",
          "checkIn": "check-in",
        }
      };
}